spring:
  application:
    name: smart-city-app
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/smartcity}
    username: ${DB_USERNAME:smartcity}
    password: ${DB_PASSWORD:smartcity}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: ${SERVER_PORT:8080}

app:
  storage:
    root: ${APP_STORAGE_ROOT:./uploads}
  oauth:
    google:
      client-id: ${GOOGLE_CLIENT_ID:}
  transport:
    data-path: ${TRANSPORT_DATA_PATH:../Testing Materials/linia_4.json} /// momentan
  security:
    jwt:
      secret: ${JWT_SECRET:ZkFrZUJhc2U2NEtleUZvclNtYXJ0Q2l0eUFwcEJhY2tlbmQxMjM0NTY3ODkwMTIzNDU2Nzg=}
      access-token-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:900000}
      refresh-token-expiration-days: ${JWT_REFRESH_EXPIRATION_DAYS:7}
