services:
  postgres:
    image: postgres:16
    container_name: smart-city-postgres
    environment:
      POSTGRES_DB: smartcity
      POSTGRES_USER: smartcity
      POSTGRES_PASSWORD: smartcity
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
